### ISSUE TITLE
Clean up url parameters

### ISSUE THREAD

**Issue by grischard** [Nanohenry10-9/Buster.lu#2]
https://buster.lu/?s=200404028&n=Bonnevoie,%20Neufch%C3%A2teau&lat=6.140648&lon=49.590494

→ 

https://buster.lu/#/Bonnevoie,%20Neufch%C3%A2teau

**Comment by grischard** [comment]
@Nanohenry10-9 it looks like permalinks don't work anymore with the new UI in any case?

**Comment by Nanohenry10-9** [comment]
Yep.

But I do think it would still be a good idea to allow those permalinks that you could copy from the page (permalink icon next to the stop name perhaps?) and then reopen later. I'll implement something over the weekend.

**Comment by Nanohenry10-9** [comment]
Alright, now you should be able to link to pages. For example: https://www.buster.lu/stop.html?name=Kirchberg,%20Universit%C3%A9it.

Fun fact: if you use the name parameter, it performs a search from all stops. That means that you can craft shorter links that give the correct result. For the stop in the above link, https://www.buster.lu/stop.html?name=kir%20un also works.

**Comment by grischard** [comment]
That's quite an elegant solution!
