### ISSUE TITLE
Clicking on bus stop name does not do anything

### ISSUE THREAD

**Issue by MrJarnould** [Nanohenry10-9/Buster.lu#5]
Clicking on the “locate me” button produces a list of names of close by bus stops. However, clicking on the bus stop name no longer displays a list of upcoming buses for said bus stop.

![FFCEB340-BDB7-4C0B-8377-3A46DA0A671E](https://user-images.githubusercontent.com/25063422/57572290-5e33c900-7418-11e9-8365-edd2640f651d.jpeg)

**Comment by Nanohenry10-9** [comment]
This was related to #4, and is now fixed with an interface update.
